# Configuration for Metaxis

migrationDir: pg_migrations
backend: postgres 

# PostgreSQL connection settings
postgres:
  host: localhost
  port: 5432
  user: tim 
  password: ""
  database: metaxis_db
